name: Debug CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Show environment
      run: |
        echo "GitHub workspace: $GITHUB_WORKSPACE"
        echo "GitHub ref: $GITHUB_REF"
        echo "GitHub event name: $GITHUB_EVENT_NAME"
        echo "GitHub repository: $GITHUB_REPOSITORY"
        echo "GitHub actor: $GITHUB_ACTOR"
        echo "GitHub SHA: $GITHUB_SHA"
        echo "GitHub run ID: $GITHUB_RUN_ID"
        echo "GitHub run number: $GITHUB_RUN_NUMBER"
        echo "GitHub workflow: $GITHUB_WORKFLOW"
        
    - name: Show system info
      run: |
        echo "Operating system: $(uname -a)"
        echo "Node.js version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Free disk space: $(df -h)"
        echo "Free memory: $(free -h)"
        
    - name: List files
      run: |
        echo "Root directory:"
        ls -la
        echo "GitHub directory:"
        ls -la .github
        echo "GitHub workflows directory:"
        ls -la .github/workflows
        
    - name: Check package.json
      run: |
        echo "Package.json content:"
        cat package.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build