name: Dependency Review

# Temporarily disable this workflow until we can fix the dependency issues
on:
  workflow_dispatch:
    # Only run manually for now

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical