name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies and build
      run: npm run ci
    
    - name: Package all platforms
      run: npm run package:all
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/openstudio-mcp-server-win.exe
          ./bin/openstudio-mcp-server-mac
          ./bin/openstudio-mcp-server-linux
        draft: false
        prerelease: false